FROM node:22-alpine AS builder

WORKDIR /app
COPY package.json /app/package.json
RUN npm install

COPY . /app
RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
